### ISSUE TITLE
Adding a key through the Plugin messes up yml files

### ISSUE THREAD

**Issue by Xirado** [marhali/easy-i18n#173]
Whenever i add a key through EasyI18n, it messes up the indentation of yml files (Usually the last key in the file)

Before
```yml
commands:
  setxpcard:
    too_large: File is too large! The maximum allowed size is {size}.
    success: Your background has been updated!
    invalid_upload: 'Invalid file extension! Valid extensions are: {extensions}'
```

After
```yml
commands:
  setxpcard:
    too_large: File is too large! The maximum allowed size is {size}.
    success: Your background has been updated!
        foo: Test
        invalid_upload: 'Invalid file extension! Valid extensions are: {extensions}'
```
