### ISSUE TITLE
Translation in single file

### ISSUE THREAD

**Issue by pieterzeilstra** [marhali/easy-i18n#174]
Hey first of all this plugin looks awesome!

My project contains all translations in a single yaml file instead of yaml files divided by language like this:
```
language_nl:
  tenants:
    styleguide: example

language_en:
  tenants:
    styleguide: example
```
Right now I don't think there is a way for this plugin to recognize different languages in one single file and my question is: am i missing something or is this not possible in this plugin?
