### ISSUE TITLE
YAML sorting is messed up

### ISSUE THREAD

**Issue by xurei** [marhali/easy-i18n#284]
When I try to add/edit the translations in the Table View, the YAML files produced are not sorted anymore.

Here are two samples of one of my YAML files:

**Before**
```yaml
aaa.bbb: AAA BBB
common.abort: Abort
common.battery: Battery
common.cancel: Cancel
common.change: Change
common.close: Close
common.connect: Connect
common.connected: Connected
common.no: No
common.ok: OK
common.retry: Retry
common.status: Status
common.today: Today
common.unknown: Unknown
common.yes: Yes
common.yesterday: Yesterday
```

**After adding "common.test"**
```yaml
common.cancel: Cancel
common.status: Status
common.battery: Battery
common.connect: Connect
common.test: Test
common.change: Change
common.no: 'No'
common.yesterday: Yesterday
common.close: Close
common.retry: Retry
common.yes: 'Yes'
common.ok: OK
common.today: Today
common.unknown: Unknown
common.abort: Abort
aaa.bbb: AAA BBB
common.connected: Connected
```

My guess is a Map<> is reordering the keys somehow.
This does not happen with JSON files.
