### ISSUE TITLE
[Feature Request] Ignore/skip initial YML key (Translation.io support)

### ISSUE THREAD

**Issue by JordanFinch72** [marhali/easy-i18n#469]
## Problem

We use Translation.io to handle translations, and each of our `en.yml`, `nl.yml`, etc. files begin with their respective key in order to support this. For example:

**en.yml**
```yml
en:
  activerecord:
    errors:
      messages:
        invalid_path: is not a valid path
```

**nl.yml**
```yml
nl:
  activerecord:
    errors:
      messages:
        invalid_path: is geen geldig pad
```

Due to this, Easy i18n believes that all of these translation keys are missing translations in the other languages.

<img width="298" alt="Image" src="https://github.com/user-attachments/assets/96211deb-c537-4767-be0b-f2c6034bf3c1" />

This tool looks very promising and looks like it would be extremely helpful. If this problem could be solved, we would be extremely grateful.

## Potential Solutions

- Add support for skipping initial keys (in our case, the first level).
