### ISSUE TITLE
Yaml translations behavior is inconsistent when key contains dots

### ISSUE THREAD

**Issue by SanderKnauff** [marhali/easy-i18n#73]
When a translation key has a dot in the name, the plugin is not able to read the value of that key.
It does recognize the existence of the key, however it will report it as missing for the language.

## Example:

Consider the following two translation files:

en.yaml
```yaml
base:
  firstKey: 'value'
  second.key: 'other value'
  missing.key: 'value missing in nl'
```

nl.yaml
```yaml
base:
  firstKey: 'waarde'
  second.key: 'hello'
  second:
    key: 'andere waarde'
```

easy-i18n interprets this as such:
![image](https://user-images.githubusercontent.com/7213734/148248405-a53ac15d-2061-41e8-9da2-7d80897bbf8b.png)
and 
![image](https://user-images.githubusercontent.com/7213734/148250081-f663ecc5-023c-474d-9d3c-4400e8e020b1.png)

In addition, trying to edit `second: key: ...` will show the value of `second.key: ...`
![image](https://user-images.githubusercontent.com/7213734/148250899-88dad2d4-69ce-463a-9704-46614c29a3cf.png)

While the dot in the key does technically does not mean anything in the YAML spec, the plugin should be able to handle these cases by either:
1. Considering the dot as a separator (making `second.key: ...` and `second: key: ...` equivalent)
2. Handling these two cases as separate values

Personally, I feel like the second should be the case as YAML disallows duplicate keys in the same object, but does allow the "same" name when nesting.
